SELECT
    comp_na_daily_all.funda.costat AS "(costat) Active/Inactive Status Marker",
    comp_na_daily_all.funda.curcd AS "(curcd) ISO Currency Code",
    comp_na_daily_all.funda.datafmt AS "(datafmt) Data Format",
    comp_na_daily_all.funda.indfmt AS "(indfmt) Industry Format",
    comp_na_daily_all.funda.consol AS "(consol) Level of Consolidation - Company Annual Descriptor",
    comp_na_daily_all.funda.tic AS "(tic) Ticker Symbol",
    comp_na_daily_all.funda.datadate AS "(datadate) Data Date",
    comp_na_daily_all.funda.gvkey AS "(gvkey) Global Company Key",
    comp_na_daily_all.funda.conm AS "(conm) Company Name",
    comp_na_daily_all.funda.cusip AS "(cusip) CUSIP",
    comp_na_daily_all.funda.cik AS "(cik) CIK Number",
    comp_na_daily_all.funda.exchg AS "(exchg) Stock Exchange Code",
    comp_na_daily_all.funda.fyr AS "(fyr) Fiscal Year-end Month",
    comp_na_daily_all.funda.fic AS "(fic) Current ISO Country Code - Incorporation",
    comp_na_daily_all.funda.acco AS "(acco) Acceptances Outstanding",
    comp_na_daily_all.funda.acdo AS "(acdo) Current Assets of Discontinued Operations",
    comp_na_daily_all.funda.aco AS "(aco) Current Assets - Other - Total",
    comp_na_daily_all.funda.acodo AS "(acodo) Other Current Assets Excl Discontinued Operations",
    comp_na_daily_all.funda.acominc AS "(acominc) Accumulated Other Comprehensive Income (Loss)",
    comp_na_daily_all.funda.acox AS "(acox) Current Assets - Other - Sundry",
    comp_na_daily_all.funda.acoxar AS "(acoxar) Current Assets - Other - Total As Reported",
    comp_na_daily_all.funda.act AS "(act) Current Assets - Total",
    comp_na_daily_all.funda.aedi AS "(aedi) Accrued Expenses and Deferred Income",
    comp_na_daily_all.funda.aldo AS "(aldo) Long-term Assets of Discontinued Operations",
    comp_na_daily_all.funda.ao AS "(ao) Assets - Other",
    comp_na_daily_all.funda.aocidergl AS "(aocidergl) Accum Other Comp Inc - Derivatives Unrealized Gain/Loss",
    comp_na_daily_all.funda.aociother AS "(aociother) Accum Other Comp Inc - Other Adjustments",
    comp_na_daily_all.funda.aocipen AS "(aocipen) Accum Other Comp Inc - Min Pension Liab Adj",
    comp_na_daily_all.funda.aocisecgl AS "(aocisecgl) Accum Other Comp Inc - Unreal G/L Ret Int in Sec Assets",
    comp_na_daily_all.funda.aodo AS "(aodo) Other Assets excluding Discontinued Operations",
    comp_na_daily_all.funda.aox AS "(aox) Assets - Other - Sundry",
    comp_na_daily_all.funda.ap AS "(ap) Accounts Payable - Trade",
    comp_na_daily_all.funda.apb AS "(apb) Accounts Payable/Creditors - Brokers, Dealers, and Clearing Organizations",
    comp_na_daily_all.funda.apc AS "(apc) Accounts Payable/Creditors - Customer",
    comp_na_daily_all.funda.apofs AS "(apofs) Accounts Payable/Creditors - Other - FS",
    comp_na_daily_all.funda.arb AS "(arb) Accounts Receivable/Debtors - Brokers, Dealers, and Clearing Organizations",
    comp_na_daily_all.funda.arc AS "(arc) Accounts Receivable/Debtors - Customer",
    comp_na_daily_all.funda.artfs AS "(artfs) Accounts Receivable/Debtors - Total",
    comp_na_daily_all.funda.at AS "(at) Assets - Total",
    comp_na_daily_all.funda.bast AS "(bast) Average Short-Term Borrowings",
    comp_na_daily_all.funda.bkvlps AS "(bkvlps) Book Value Per Share",
    comp_na_daily_all.funda.ca AS "(ca) Customers'' Acceptance",
    comp_na_daily_all.funda.caps AS "(caps) Capital Surplus/Share Premium Reserve",
    comp_na_daily_all.funda.cb AS "(cb) Compensating Balance",
    comp_na_daily_all.funda.ceq AS "(ceq) Common/Ordinary Equity - Total",
    comp_na_daily_all.funda.ceql AS "(ceql) Common Equity - Liquidation Value",
    comp_na_daily_all.funda.ceqt AS "(ceqt) Common Equity - Tangible",
    comp_na_daily_all.funda.ch AS "(ch) Cash",
    comp_na_daily_all.funda.che AS "(che) Cash and Short-Term Investments",
    comp_na_daily_all.funda.chs AS "(chs) Cash and Deposits - Segregated",
    comp_na_daily_all.funda.cld2 AS "(cld2) Capitalized Leases - Due in 2nd Year",
    comp_na_daily_all.funda.cld3 AS "(cld3) Capitalized Leases - Due in 3rd Year",
    comp_na_daily_all.funda.cld4 AS "(cld4) Capitalized Leases - Due in 4th Year",
    comp_na_daily_all.funda.cld5 AS "(cld5) Capitalized Leases - Due in 5th Year",
    comp_na_daily_all.funda.clfc AS "(clfc) Contingent Liabilities - Forward and Future Contracts",
    comp_na_daily_all.funda.clfx AS "(clfx) Contingent Liabilities - Foreign Exchange Commitments",
    comp_na_daily_all.funda.clg AS "(clg) Contingent Liabilities - Guarantees",
    comp_na_daily_all.funda.clis AS "(clis) Contingent Liabilities - Interest Rate Swaps",
    comp_na_daily_all.funda.cll AS "(cll) Contingent Liabilities - Letters of Credit",
    comp_na_daily_all.funda.cllc AS "(cllc) Contingent Liabilities - Loan Commitments",
    comp_na_daily_all.funda.clo AS "(clo) Contingent Liabilities - Other",
    comp_na_daily_all.funda.clrll AS "(clrll) Credit Loss Reserve Allocated for LDC Loans",
    comp_na_daily_all.funda.clt AS "(clt) Contingent Liabilities - Total",
    comp_na_daily_all.funda.cmp AS "(cmp) Commercial Paper",
    comp_na_daily_all.funda.crv AS "(crv) Consolidation Reserves",
    comp_na_daily_all.funda.crvnli AS "(crvnli) Reserves for Claims (Losses) - Nonlife (Insurance)",
    comp_na_daily_all.funda.cstk AS "(cstk) Common/Ordinary Stock (Capital)",
    comp_na_daily_all.funda.cstkcv AS "(cstkcv) Common Stock-Carrying Value",
    comp_na_daily_all.funda.dc AS "(dc) Deferred Charges",
    comp_na_daily_all.funda.dclo AS "(dclo) Debt - Capitalized Lease Obligations",
    comp_na_daily_all.funda.dcom AS "(dcom) Deferred Compensation",
    comp_na_daily_all.funda.dcpstk AS "(dcpstk) Convertible Debt and Preferred Stock",
    comp_na_daily_all.funda.dcs AS "(dcs) Debt - Consolidated Subsidiary",
    comp_na_daily_all.funda.dcvsr AS "(dcvsr) Debt - Senior Convertible",
    comp_na_daily_all.funda.dcvsub AS "(dcvsub) Debt - Subordinated Convertible",
    comp_na_daily_all.funda.dcvt AS "(dcvt) Debt - Convertible",
    comp_na_daily_all.funda.dd AS "(dd) Debt - Debentures",
    comp_na_daily_all.funda.dd1 AS "(dd1) Long-Term Debt Due in One Year",
    comp_na_daily_all.funda.dd2 AS "(dd2) Debt - Due in 2nd Year",
    comp_na_daily_all.funda.dd3 AS "(dd3) Debt - Due in 3rd Year",
    comp_na_daily_all.funda.dd4 AS "(dd4) Debt - Due in 4th Year",
    comp_na_daily_all.funda.dd5 AS "(dd5) Debt - Due in 5th Year",
    comp_na_daily_all.funda.dfpac AS "(dfpac) Deferred Policy Acquisition Costs",
    comp_na_daily_all.funda.dfs AS "(dfs) Debt - Finance Subsidiary",
    comp_na_daily_all.funda.dlc AS "(dlc) Debt in Current Liabilities - Total",
    comp_na_daily_all.funda.dlto AS "(dlto) Other Long-term Debt",
    comp_na_daily_all.funda.dltp AS "(dltp) Long-Term Debt - Tied to Prime",
    comp_na_daily_all.funda.dltsub AS "(dltsub) Long-Term Debt - Subordinated",
    comp_na_daily_all.funda.dltt AS "(dltt) Long-Term Debt - Total",
    comp_na_daily_all.funda.dm AS "(dm) Debt - Mortgages & Other Secured",
    comp_na_daily_all.funda.dn AS "(dn) Debt - Notes",
    comp_na_daily_all.funda.dpacb AS "(dpacb) Depreciation (Accumulated) - Buildings",
    comp_na_daily_all.funda.dpacc AS "(dpacc) Depreciation (Accumulated) - Construction in Progress",
    comp_na_daily_all.funda.dpacli AS "(dpacli) Depreciation (Accumulated) - Land and Improvements",
    comp_na_daily_all.funda.dpacls AS "(dpacls) Depreciation (Accumulated) - Leases",
    comp_na_daily_all.funda.dpacme AS "(dpacme) Depreciation (Accumulated) - Machinery and Equipment",
    comp_na_daily_all.funda.dpacnr AS "(dpacnr) Depreciation (Accumulated) - Natural Resources",
    comp_na_daily_all.funda.dpaco AS "(dpaco) Depreciation (Accumulated) - Other",
    comp_na_daily_all.funda.dpacre AS "(dpacre) Accumulated Depreciation of RE Property",
    comp_na_daily_all.funda.dpact AS "(dpact) Depreciation, Depletion and Amortization (Accumulated)",
    comp_na_daily_all.funda.dpdc AS "(dpdc) Deposits - Demand - Customer",
    comp_na_daily_all.funda.dpltb AS "(dpltb) Deposits - Long-Term Time - Bank",
    comp_na_daily_all.funda.dpsc AS "(dpsc) Deposits - Savings - Customer",
    comp_na_daily_all.funda.dpstb AS "(dpstb) Deposits - Short-Term Demand - Bank",
    comp_na_daily_all.funda.dptb AS "(dptb) Deposits - Total - Banks",
    comp_na_daily_all.funda.dptc AS "(dptc) Deposits - Total - Customer",
    comp_na_daily_all.funda.dptic AS "(dptic) Deposits - Time - Customer",
    comp_na_daily_all.funda.dpvieb AS "(dpvieb) Depreciation (Accumulated) - Ending Balance (Schedule VI)",
    comp_na_daily_all.funda.dpvio AS "(dpvio) Depreciation (Accumulated) - Other Changes (Schedule VI)",
    comp_na_daily_all.funda.dpvir AS "(dpvir) Depreciation (Accumulated) - Retirements (Schedule VI)",
    comp_na_daily_all.funda.drc AS "(drc) Deferred Revenue - Current",
    comp_na_daily_all.funda.drci AS "(drci) Deduction From Policy and Claims Reserves for Reinsurance Ceded",
    comp_na_daily_all.funda.drlt AS "(drlt) Deferred Revenue - Long-term",
    comp_na_daily_all.funda.ds AS "(ds) Debt-Subordinated",
    comp_na_daily_all.funda.dudd AS "(dudd) Debt - Unamortized Debt Discount and Other",
    comp_na_daily_all.funda.dvpa AS "(dvpa) Preferred Dividends in Arrears",
    comp_na_daily_all.funda.dvpibb AS "(dvpibb) Depreciation (Accumulated) - Beginning Balance (Schedule VI)",
    comp_na_daily_all.funda.dxd2 AS "(dxd2) Debt (excl Capitalized Leases) - Due in 2nd Year",
    comp_na_daily_all.funda.dxd3 AS "(dxd3) Debt (excl Capitalized Leases) - Due in 3rd Year",
    comp_na_daily_all.funda.dxd4 AS "(dxd4) Debt (excl Capitalized Leases) - Due in 4th Year",
    comp_na_daily_all.funda.dxd5 AS "(dxd5) Debt (excl Capitalized Leases) - Due in 5th Year",
    comp_na_daily_all.funda.ea AS "(ea) Exchange Adjustments (Assets)",
    comp_na_daily_all.funda.esopct AS "(esopct) Common ESOP Obligation - Total",
    comp_na_daily_all.funda.esopdlt AS "(esopdlt) ESOP Debt - Long Term",
    comp_na_daily_all.funda.esopnr AS "(esopnr) Preferred ESOP Obligation - Non-Redeemable",
    comp_na_daily_all.funda.esopr AS "(esopr) Preferred ESOP Obligation - Redeemable",
    comp_na_daily_all.funda.esopt AS "(esopt) Preferred ESOP Obligation - Total",
    comp_na_daily_all.funda.excadj AS "(excadj) Exchange Adjustments (Liabilities)",
    comp_na_daily_all.funda.fatb AS "(fatb) Property, Plant, and Equipment - Buildings at Cost",
    comp_na_daily_all.funda.fatc AS "(fatc) Property, Plant, and Equipment - Construction in Progress at Cost",
    comp_na_daily_all.funda.fate AS "(fate) Property, Plant, and Equipment - Machinery and Equipment at Cost",
    comp_na_daily_all.funda.fatl AS "(fatl) Property, Plant, and Equipment - Leases at Cost",
    comp_na_daily_all.funda.fatn AS "(fatn) Property, Plant, and Equipment - Natural Resources at Cost",
    comp_na_daily_all.funda.fato AS "(fato) Property, Plant, and Equipment - Other at Cost",
    comp_na_daily_all.funda.fatp AS "(fatp) Property, Plant, and Equipment - Land and Improvements at Cost",
    comp_na_daily_all.funda.fdfr AS "(fdfr) Federal Funds Purchased",
    comp_na_daily_all.funda.fea AS "(fea) Foreign Exchange Assets",
    comp_na_daily_all.funda.fel AS "(fel) Foreign Exchange Liabilities",
    comp_na_daily_all.funda.ffs AS "(ffs) Federal Funds Sold",
    comp_na_daily_all.funda.gdwl AS "(gdwl) Goodwill",
    comp_na_daily_all.funda.geqrv AS "(geqrv) Grants - Equity Reserves",
    comp_na_daily_all.funda.govgr AS "(govgr) Government Grants",
    comp_na_daily_all.funda.iaeq AS "(iaeq) Investment Assets - Equity Securities (Insurance)",
    comp_na_daily_all.funda.iaeqci AS "(iaeqci) Investment Assets (Insurance) - Equity Securities (Cost)",
    comp_na_daily_all.funda.iaeqmi AS "(iaeqmi) Investment Assets (Insurance) - Equity Securities (Market)",
    comp_na_daily_all.funda.iafici AS "(iafici) Investment Assets (Insurance) - Fixed Income Securities (Cost)",
    comp_na_daily_all.funda.iafxi AS "(iafxi) Investment Assets - Fixed Income Securities (Insurance)",
    comp_na_daily_all.funda.iafxmi AS "(iafxmi) Investment Assets (Insurance) - Fixed Income Securities (Market)",
    comp_na_daily_all.funda.iali AS "(iali) Investment Assets (Insurance) - Listed Securities-Total",
    comp_na_daily_all.funda.ialoi AS "(ialoi) Investment Assets - Loans - Other (Insurance)",
    comp_na_daily_all.funda.ialti AS "(ialti) Investment Assets - Loans - Total (Insurance)",
    comp_na_daily_all.funda.iamli AS "(iamli) Investment Assets - Mortgage Loans (Insurance)",
    comp_na_daily_all.funda.iaoi AS "(iaoi) Investment Assets - Other (Insurance)",
    comp_na_daily_all.funda.iapli AS "(iapli) Investment Assets - Policy Loans (Insurance)",
    comp_na_daily_all.funda.iarei AS "(iarei) Investment Assets - Real Estate (Insurance)",
    comp_na_daily_all.funda.iasci AS "(iasci) Investment Assets (Insurance) - Securities - Sundry (Cost)",
    comp_na_daily_all.funda.iasmi AS "(iasmi) Investment Assets (Insurance) - Securities - Sundry (Market)",
    comp_na_daily_all.funda.iassi AS "(iassi) Investment Assets - Securities - Sundry (Insurance)",
    comp_na_daily_all.funda.iasti AS "(iasti) Investment Assets - Securities - Total (Insurance)",
    comp_na_daily_all.funda.iatci AS "(iatci) Investment Assets (Insurance) - Securities - Total (Cost)",
    comp_na_daily_all.funda.iati AS "(iati) Investment Assets - Total (Insurance)",
    comp_na_daily_all.funda.iatmi AS "(iatmi) Investment Assets (Insurance) - Securities - Total (Market)",
    comp_na_daily_all.funda.iaui AS "(iaui) Investment Assets (Insurance) - Unlisted Securities - Total",
    comp_na_daily_all.funda.icapt AS "(icapt) Invested Capital - Total",
    comp_na_daily_all.funda.intan AS "(intan) Intangible Assets - Total",
    comp_na_daily_all.funda.intano AS "(intano) Other Intangibles",
    comp_na_daily_all.funda.invfg AS "(invfg) Inventories - Finished Goods",
    comp_na_daily_all.funda.invo AS "(invo) Inventories - Other",
    comp_na_daily_all.funda.invofs AS "(invofs) Inventory/Stock - Other",
    comp_na_daily_all.funda.invreh AS "(invreh) Inventory/Stock - Real Estate Held for Development",
    comp_na_daily_all.funda.invrei AS "(invrei) Inventory/Stock - Real Estate Under Development",
    comp_na_daily_all.funda.invres AS "(invres) Inventory/Stock - Real Estate Held for Sale",
    comp_na_daily_all.funda.invrm AS "(invrm) Inventories - Raw Materials",
    comp_na_daily_all.funda.invt AS "(invt) Inventories - Total",
    comp_na_daily_all.funda.invwip AS "(invwip) Inventories - Work In Process",
    comp_na_daily_all.funda.ip AS "(ip) Investment Property",
    comp_na_daily_all.funda.ipc AS "(ipc) Investment Property (Cost)",
    comp_na_daily_all.funda.ipv AS "(ipv) Investment Property (Valuation)",
    comp_na_daily_all.funda.iseq AS "(iseq) Investment Securities - Equity",
    comp_na_daily_all.funda.iseqc AS "(iseqc) Investment Securities - Equity (Cost)",
    comp_na_daily_all.funda.iseqm AS "(iseqm) Investment Securities - Equity (Market)",
    comp_na_daily_all.funda.isfi AS "(isfi) Investment Securities - Fixed Income",
    comp_na_daily_all.funda.isfxc AS "(isfxc) Investment Securities - Fixed Income (Cost)",
    comp_na_daily_all.funda.isfxm AS "(isfxm) Investment Securities - Fixed Income (Market)",
    comp_na_daily_all.funda.islg AS "(islg) Investment Securities - Local Governments",
    comp_na_daily_all.funda.islgc AS "(islgc) Investment Securities - Local Governments (Cost)",
    comp_na_daily_all.funda.islgm AS "(islgm) Investment Securities - Local Governments (Market)",
    comp_na_daily_all.funda.islt AS "(islt) Investment Securities - Listed - Total",
    comp_na_daily_all.funda.isng AS "(isng) Investment Securities - National Governments",
    comp_na_daily_all.funda.isngc AS "(isngc) Investment Securities - National Governments (Cost)",
    comp_na_daily_all.funda.isngm AS "(isngm) Investment Securities - National Governments (Market)",
    comp_na_daily_all.funda.isotc AS "(isotc) Invetsment Securities - Other (Cost)",
    comp_na_daily_all.funda.isoth AS "(isoth) Investment Securities - Other",
    comp_na_daily_all.funda.isotm AS "(isotm) Invetsment Securities - Other (Market)",
    comp_na_daily_all.funda.issc AS "(issc) Investment Securities - Sundry (Cost)",
    comp_na_daily_all.funda.issm AS "(issm) Investment Securities - Sundry (Market)",
    comp_na_daily_all.funda.issu AS "(issu) Investment Securities - Sundry",
    comp_na_daily_all.funda.ist AS "(ist) Investment Securities -Total",
    comp_na_daily_all.funda.istc AS "(istc) Investment Securities - Total (Cost)",
    comp_na_daily_all.funda.istm AS "(istm) Investment Securities - Total (Market)",
    comp_na_daily_all.funda.isut AS "(isut) Investment Securities - Unlisted - Total",
    comp_na_daily_all.funda.itcb AS "(itcb) Investment Tax Credit (Balance Sheet)",
    comp_na_daily_all.funda.ivaeq AS "(ivaeq) Investment and Advances - Equity",
    comp_na_daily_all.funda.ivao AS "(ivao) Investment and Advances - Other",
    comp_na_daily_all.funda.ivgod AS "(ivgod) Investments Grants and Other Deductions",
    comp_na_daily_all.funda.ivpt AS "(ivpt) Investments - Permanent - Total",
    comp_na_daily_all.funda.ivst AS "(ivst) Short-Term Investments - Total",
    comp_na_daily_all.funda.lcabg AS "(lcabg) Loans/Claims/Advances - Banks and Government - Total",
    comp_na_daily_all.funda.lcacl AS "(lcacl) Loans/Claims/Advances - Commercial",
    comp_na_daily_all.funda.lcacr AS "(lcacr) Loans/Claims/Advances - Consumer",
    comp_na_daily_all.funda.lcag AS "(lcag) Loans/Claims/Advances - Government",
    comp_na_daily_all.funda.lcal AS "(lcal) Loans/Claims/Advances - Lease",
    comp_na_daily_all.funda.lcalt AS "(lcalt) Loans/Claims/Advances - Long-Term (Banks)",
    comp_na_daily_all.funda.lcam AS "(lcam) Loans/Claims/Advances - Mortgage",
    comp_na_daily_all.funda.lcao AS "(lcao) Loans/Claims/Advances - Other",
    comp_na_daily_all.funda.lcast AS "(lcast) Loans/Claims/Advances - Short-Term - Banks",
    comp_na_daily_all.funda.lcat AS "(lcat) Loans/Claims/Advances - Total",
    comp_na_daily_all.funda.lco AS "(lco) Current Liabilities - Other - Total",
    comp_na_daily_all.funda.lcox AS "(lcox) Current Liabilities - Other - Sundry",
    comp_na_daily_all.funda.lcoxar AS "(lcoxar) Current Liabilities - Other - Total As Reported",
    comp_na_daily_all.funda.lcoxdr AS "(lcoxdr) Current Liabilities - Other - Excluding Deferred Revenue",
    comp_na_daily_all.funda.lct AS "(lct) Current Liabilities - Total",
    comp_na_daily_all.funda.lcuacu AS "(lcuacu) Loans/Claims/Advances - Customer - Total",
    comp_na_daily_all.funda.lif AS "(lif) Life Insurance in Force",
    comp_na_daily_all.funda.lifr AS "(lifr) LIFO Reserve",
    comp_na_daily_all.funda.lloml AS "(lloml) LDC Loans Outstanding - Medium and Long-Term",
    comp_na_daily_all.funda.lloo AS "(lloo) LDC Loans Outstanding - Other",
    comp_na_daily_all.funda.llot AS "(llot) LDC Loans Outstanding - Total",
    comp_na_daily_all.funda.lo AS "(lo) Liabilities - Other - Total",
    comp_na_daily_all.funda.loxdr AS "(loxdr) Liabilities - Other - Excluding Deferred Revenue",
    comp_na_daily_all.funda.lrv AS "(lrv) Legal Reserves",
    comp_na_daily_all.funda.ls AS "(ls) Liabilities - Other - Sundry",
    comp_na_daily_all.funda.lse AS "(lse) Liabilities and Stockholders Equity - Total",
    comp_na_daily_all.funda.lt AS "(lt) Liabilities - Total",
    comp_na_daily_all.funda.mib AS "(mib) Noncontrolling Interest (Balance Sheet)",
    comp_na_daily_all.funda.mrc1 AS "(mrc1) Rental Commitments - Minimum - 1st Year",
    comp_na_daily_all.funda.mrc2 AS "(mrc2) Rental Commitments - Minimum - 2nd Year",
    comp_na_daily_all.funda.mrc3 AS "(mrc3) Rental Commitments - Minimum - 3rd Year",
    comp_na_daily_all.funda.mrc4 AS "(mrc4) Rental Commitments - Minimum - 4th Year",
    comp_na_daily_all.funda.mrc5 AS "(mrc5) Rental Commitments - Minimum - 5th Year",
    comp_na_daily_all.funda.mrct AS "(mrct) Rental Commitments - Minimum - 5 Year Total",
    comp_na_daily_all.funda.mrcta AS "(mrcta) Thereafter Portion of Leases",
    comp_na_daily_all.funda.msa AS "(msa) Marketable Securities Adjustment",
    comp_na_daily_all.funda.msvrv AS "(msvrv) Mandatory Securities Valuation Reserve (Statutory)",
    comp_na_daily_all.funda.mtl AS "(mtl) Loans From Securities Finance Companies for Margin Transactions",
    comp_na_daily_all.funda.nat AS "(nat) Nonadmitted Assets - Total (Statutory)",
    comp_na_daily_all.funda.np AS "(np) Notes Payable - Short-Term Borrowings",
    comp_na_daily_all.funda.npanl AS "(npanl) Nonperforming Assets - Nonaccrual Loans",
    comp_na_daily_all.funda.npaore AS "(npaore) Nonperforming Assets - Other Real Estate Owned",
    comp_na_daily_all.funda.nparl AS "(nparl) Nonperforming Assets - Restructured Loans",
    comp_na_daily_all.funda.npat AS "(npat) Nonperforming Assets - Total",
    comp_na_daily_all.funda.ob AS "(ob) Order Backlog",
    comp_na_daily_all.funda.optprcca AS "(optprcca) Options Cancelled - Price",
    comp_na_daily_all.funda.optprcex AS "(optprcex) Options Exercised - Price",
    comp_na_daily_all.funda.optprcey AS "(optprcey) Options Outstanding End of Year - Price",
    comp_na_daily_all.funda.optprcgr AS "(optprcgr) Options Granted - Price",
    comp_na_daily_all.funda.optprcwa AS "(optprcwa) Options Exercisable - Weighted Avg Price",
    comp_na_daily_all.funda.ppegt AS "(ppegt) Property, Plant and Equipment - Total (Gross)",
    comp_na_daily_all.funda.ppenb AS "(ppenb) Property, Plant, and Equipment - Buildings (Net)",
    comp_na_daily_all.funda.ppenc AS "(ppenc) Property, Plant, and Equipment - Construction in Progress (Net)",
    comp_na_daily_all.funda.ppenli AS "(ppenli) Property, Plant, and Equipment - Land and Improvements (Net)",
    comp_na_daily_all.funda.ppenls AS "(ppenls) Property, Plant, and Equipment - Leases (Net)",
    comp_na_daily_all.funda.ppenme AS "(ppenme) Property, Plant, and Equipment - Machinery and Equipment (Net)",
    comp_na_daily_all.funda.ppennr AS "(ppennr) Property, Plant, and Equipment - Natural Resources (Net)",
    comp_na_daily_all.funda.ppeno AS "(ppeno) Property, Plant, and Equipment - Other (Net)",
    comp_na_daily_all.funda.ppent AS "(ppent) Property, Plant and Equipment - Total (Net)",
    comp_na_daily_all.funda.ppevbb AS "(ppevbb) Property, Plant and Equipment - Beginning Balance (Schedule V)",
    comp_na_daily_all.funda.ppeveb AS "(ppeveb) Property, Plant, and Equipment - Ending Balance (Schedule V)",
    comp_na_daily_all.funda.ppevo AS "(ppevo) Property, Plant, and Equipment - Other Changes (Schedule V)",
    comp_na_daily_all.funda.ppevr AS "(ppevr) Property, Plant and Equipment - Retirements (Schedule V)",
    comp_na_daily_all.funda.prc AS "(prc) Participation Rights Certificates",
    comp_na_daily_all.funda.prodv AS "(prodv) Proposed Dividends",
    comp_na_daily_all.funda.prvt AS "(prvt) Policy Reserves - Total (Statutory)",
    comp_na_daily_all.funda.pstk AS "(pstk) Preferred/Preference Stock (Capital) - Total",
    comp_na_daily_all.funda.pstkc AS "(pstkc) Preferred Stock - Convertible",
    comp_na_daily_all.funda.pstkl AS "(pstkl) Preferred Stock - Liquidating Value",
    comp_na_daily_all.funda.pstkn AS "(pstkn) Preferred/Preference Stock - Nonredeemable",
    comp_na_daily_all.funda.pstkr AS "(pstkr) Preferred/Preference Stock - Redeemable",
    comp_na_daily_all.funda.pstkrv AS "(pstkrv) Preferred Stock - Redemption Value",
    comp_na_daily_all.funda.pvcl AS "(pvcl) Provision - Credit Losses (Balance Sheet)",
    comp_na_daily_all.funda.pvpl AS "(pvpl) Provision - Pension Liabilities",
    comp_na_daily_all.funda.pvt AS "(pvt) Provisions - Total",
    comp_na_daily_all.funda.radp AS "(radp) Reinsurance Assets - Deposits and Other (Insurance)",
    comp_na_daily_all.funda.ragr AS "(ragr) Resale Agreements",
    comp_na_daily_all.funda.rari AS "(rari) Reinsurance Assets - Receivable/Debtors (Insurance)",
    comp_na_daily_all.funda.rati AS "(rati) Reinsurance Assets - Total (Insurance)",
    comp_na_daily_all.funda.rcl AS "(rcl) Reserves for Credit Losses (Assets)",
    comp_na_daily_all.funda.rdp AS "(rdp) Regulatory Deposits",
    comp_na_daily_all.funda.re AS "(re) Retained Earnings",
    comp_na_daily_all.funda.rea AS "(rea) Retained Earnings - Restatement",
    comp_na_daily_all.funda.reajo AS "(reajo) Retained Earnings - Other Adjustments",
    comp_na_daily_all.funda.recco AS "(recco) Receivables - Current - Other",
    comp_na_daily_all.funda.recd AS "(recd) Receivables - Estimated Doubtful",
    comp_na_daily_all.funda.rect AS "(rect) Receivables - Total",
    comp_na_daily_all.funda.recta AS "(recta) Retained Earnings - Cumulative Translation Adjustment",
    comp_na_daily_all.funda.rectr AS "(rectr) Receivables - Trade",
    comp_na_daily_all.funda.recub AS "(recub) Unbilled Receivables",
    comp_na_daily_all.funda.ret AS "(ret) Total RE Property",
    comp_na_daily_all.funda.reuna AS "(reuna) Retained Earnings - Unadjusted",
    comp_na_daily_all.funda.reunr AS "(reunr) Retained Earnings - Unrestricted",
    comp_na_daily_all.funda.rll AS "(rll) Reserve for Loan/Asset Losses",
    comp_na_daily_all.funda.rlo AS "(rlo) Reinsurance Liabilities - Other",
    comp_na_daily_all.funda.rlp AS "(rlp) Reinsurance Liabilities - Payables/Creditors",
    comp_na_daily_all.funda.rlri AS "(rlri) Reinsurers'' Liability for Reserves (Insurance)",
    comp_na_daily_all.funda.rlt AS "(rlt) Reinsurance Liabilities - Total",
    comp_na_daily_all.funda.rpag AS "(rpag) Repurchase Agreements",
    comp_na_daily_all.funda.rreps AS "(rreps) Reversal - Restructuring/Acq Basic EPS Effect",
    comp_na_daily_all.funda.rvbci AS "(rvbci) Reserves for Benefits - Life - Claims (Insurance)",
    comp_na_daily_all.funda.rvbpi AS "(rvbpi) Reserves for Benefits - Life - Policy (Insurance)",
    comp_na_daily_all.funda.rvbti AS "(rvbti) Reserves for Benefits - Life - Total (Insurance)",
    comp_na_daily_all.funda.rvdo AS "(rvdo) Reserves - Distributable - Other",
    comp_na_daily_all.funda.rvdt AS "(rvdt) Reserves - Distributable - Total",
    comp_na_daily_all.funda.rveqt AS "(rveqt) Equity Reserves - Total",
    comp_na_daily_all.funda.rvlrv AS "(rvlrv) Revaluation Reserve",
    comp_na_daily_all.funda.rvno AS "(rvno) Reserves - Nondistributable - Other",
    comp_na_daily_all.funda.rvnt AS "(rvnt) Reserves - Nondistributable - Total",
    comp_na_daily_all.funda.rvri AS "(rvri) Reserves - Reinsurance (Insurance)",
    comp_na_daily_all.funda.rvsi AS "(rvsi) Reserves - Sundry (Insurance)",
    comp_na_daily_all.funda.rvti AS "(rvti) Reserves - Total",
    comp_na_daily_all.funda.rvtxr AS "(rvtxr) Reserves - Tax-Regulated",
    comp_na_daily_all.funda.rvupi AS "(rvupi) Reserves for Unearned Premiums (Insurance)",
    comp_na_daily_all.funda.rvutx AS "(rvutx) Reserves - Untaxed",
    comp_na_daily_all.funda.saa AS "(saa) Separate Account Assets",
    comp_na_daily_all.funda.sal AS "(sal) Separate Account Liabilities",
    comp_na_daily_all.funda.sbdc AS "(sbdc) Securities Borrowed and Deposited by Customers",
    comp_na_daily_all.funda.sc AS "(sc) Securities In Custody",
    comp_na_daily_all.funda.sco AS "(sco) Share Capital - Other",
    comp_na_daily_all.funda.secu AS "(secu) Securities Gains (Losses) - Unrealized",
    comp_na_daily_all.funda.seq AS "(seq) Stockholders Equity - Parent",
    comp_na_daily_all.funda.seqo AS "(seqo) Other Stockholders- Equity Adjustments",
    comp_na_daily_all.funda.srt AS "(srt) Surplus - Total (Statutory)",
    comp_na_daily_all.funda.ssnp AS "(ssnp) Securities Sold Not Yet Purchased",
    comp_na_daily_all.funda.stbo AS "(stbo) Short-Term Borrowings - Other",
    comp_na_daily_all.funda.stio AS "(stio) Short-Term Investments - Other",
    comp_na_daily_all.funda.tdscd AS "(tdscd) Trading/Dealing Account Securities - Corporate Debt",
    comp_na_daily_all.funda.tdsce AS "(tdsce) Trading/Dealing Account Securities - Corporate Equity",
    comp_na_daily_all.funda.tdslg AS "(tdslg) Trading/Dealing Account Securities - Local Governments",
    comp_na_daily_all.funda.tdsmm AS "(tdsmm) Trading/Dealing Account Securities - Money Market",
    comp_na_daily_all.funda.tdsng AS "(tdsng) Trading/Dealing Account Securities - National Governments",
    comp_na_daily_all.funda.tdso AS "(tdso) Trading/Dealing Account Securities - Other",
    comp_na_daily_all.funda.tdss AS "(tdss) Trading/Dealing Account Securities - Sundry",
    comp_na_daily_all.funda.tdst AS "(tdst) Trading/Dealing Account Securities - Total",
    comp_na_daily_all.funda.tlcf AS "(tlcf) Tax Loss Carry Forward",
    comp_na_daily_all.funda.transa AS "(transa) Cumulative Translation Adjustment",
    comp_na_daily_all.funda.tsa AS "(tsa) Treasury Stock (Assets)",
    comp_na_daily_all.funda.tso AS "(tso) Treasury Stock - Other Share Capital",
    comp_na_daily_all.funda.tstk AS "(tstk) Treasury Stock - Total (All Capital)",
    comp_na_daily_all.funda.tstkc AS "(tstkc) Treasury Stock - Common",
    comp_na_daily_all.funda.tstkme AS "(tstkme) Treasury Stock Book Value - Memo Entry",
    comp_na_daily_all.funda.tstkp AS "(tstkp) Treasury Stock - Preferrred",
    comp_na_daily_all.funda.txdb AS "(txdb) Deferred Taxes (Balance Sheet)",
    comp_na_daily_all.funda.txdba AS "(txdba) Deferred Tax Asset - Long Term",
    comp_na_daily_all.funda.txdbca AS "(txdbca) Deferred Tax Asset - Current",
    comp_na_daily_all.funda.txdbcl AS "(txdbcl) Deferred Tax Liability - Current",
    comp_na_daily_all.funda.txditc AS "(txditc) Deferred Taxes and Investment Tax Credit",
    comp_na_daily_all.funda.txndb AS "(txndb) Net Deferred Tax Asset (Liab) - Total",
    comp_na_daily_all.funda.txndba AS "(txndba) Net Deferred Tax Asset",
    comp_na_daily_all.funda.txndbl AS "(txndbl) Net Deferred Tax Liability",
    comp_na_daily_all.funda.txndbr AS "(txndbr) Deferred Tax Residual",
    comp_na_daily_all.funda.txp AS "(txp) Income Taxes Payable",
    comp_na_daily_all.funda.txr AS "(txr) Income Tax Refund",
    comp_na_daily_all.funda.uaox AS "(uaox) Other Assets - Utility",
    comp_na_daily_all.funda.uapt AS "(uapt) Accounts Payable - Utility",
    comp_na_daily_all.funda.ucaps AS "(ucaps) Paid in Capital - Other",
    comp_na_daily_all.funda.uccons AS "(uccons) Contributions in Aid of Construction",
    comp_na_daily_all.funda.uceq AS "(uceq) Common Equity Total - Utility",
    comp_na_daily_all.funda.ucustad AS "(ucustad) Customer Advances for Construction",
    comp_na_daily_all.funda.udcopres AS "(udcopres) Deferred Credits and Operating Reserves - Other",
    comp_na_daily_all.funda.udd AS "(udd) Debt (Debentures)",
    comp_na_daily_all.funda.udmb AS "(udmb) Debt (Mortgage Bonds) - Utility",
    comp_na_daily_all.funda.udolt AS "(udolt) Debt (Other Long-Term) - Utility",
    comp_na_daily_all.funda.udpco AS "(udpco) Debt (Pollution Control Obligations) - Utility",
    comp_na_daily_all.funda.ui AS "(ui) Unearned Income",
    comp_na_daily_all.funda.uinvt AS "(uinvt) Inventories - Utility",
    comp_na_daily_all.funda.ulcm AS "(ulcm) Current Liabilities - Miscellaneous",
    comp_na_daily_all.funda.ulco AS "(ulco) Current Liabilities - Other - Utility",
    comp_na_daily_all.funda.unl AS "(unl) Unappropriated Net Loss",
    comp_na_daily_all.funda.unnp AS "(unnp) Unappropriated Net Profit (Stockholders'' Equity)",
    comp_na_daily_all.funda.unnpl AS "(unnpl) Unappropriated Net Profit",
    comp_na_daily_all.funda.uopres AS "(uopres) Operating Reserves",
    comp_na_daily_all.funda.upmcstk AS "(upmcstk) Premium on Common Stock*",
    comp_na_daily_all.funda.upmpf AS "(upmpf) Premium on Preferred Stock*",
    comp_na_daily_all.funda.upmpfs AS "(upmpfs) Premium on Preference Stock*",
    comp_na_daily_all.funda.upmsubp AS "(upmsubp) Premium on Subsidiary Preferred Stock*",
    comp_na_daily_all.funda.upstk AS "(upstk) Preferred Stock at Carrying Value",
    comp_na_daily_all.funda.upstkc AS "(upstkc) Preference Stock at Carrying Value*",
    comp_na_daily_all.funda.upstksf AS "(upstksf) Preferred/Preference Stock Sinking Fund Requirement",
    comp_na_daily_all.funda.urect AS "(urect) Receivables (Net)",
    comp_na_daily_all.funda.urectr AS "(urectr) Accounts Receivable - Trade - Utility",
    comp_na_daily_all.funda.urevub AS "(urevub) Accrued Unbilled Revenues (Balance Sheet)",
    comp_na_daily_all.funda.usubpstk AS "(usubpstk) Subsidiary Preferred Stock at Carrying Value",
    comp_na_daily_all.funda.vpac AS "(vpac) Investments - Permanent - Associated Companies",
    comp_na_daily_all.funda.vpo AS "(vpo) Investments - Permanent - Other",
    comp_na_daily_all.funda.wcap AS "(wcap) Working Capital (Balance Sheet)",
    comp_na_daily_all.funda.xacc AS "(xacc) Accrued Expenses",
    comp_na_daily_all.funda.xpp AS "(xpp) Prepaid Expenses",
    comp_na_daily_all.funda.acchg AS "(acchg) Accounting Changes - Cumulative Effect",
    comp_na_daily_all.funda.adpac AS "(adpac) Amortization of Deferred Policy Acquisition Costs",
    comp_na_daily_all.funda.am AS "(am) Amortization of Intangibles",
    comp_na_daily_all.funda.amdc AS "(amdc) Amortization of Deferred Charges",
    comp_na_daily_all.funda.amgw AS "(amgw) Amortization of Goodwill",
    comp_na_daily_all.funda.aqa AS "(aqa) Acquisition/Merger After-tax",
    comp_na_daily_all.funda.aqd AS "(aqd) Acquisition/Merger Diluted EPS Effect",
    comp_na_daily_all.funda.aqeps AS "(aqeps) Acquisition/Merger Basic EPS Effect",
    comp_na_daily_all.funda.aqi AS "(aqi) Acquisitions - Income Contribution",
    comp_na_daily_all.funda.aqp AS "(aqp) Acquisition/Merger Pretax",
    comp_na_daily_all.funda.aqs AS "(aqs) Acquisitions - Sales Contribution",
    comp_na_daily_all.funda.arce AS "(arce) As Reported Core - After-tax",
    comp_na_daily_all.funda.arced AS "(arced) As Reported Core - Diluted EPS Effect",
    comp_na_daily_all.funda.arceeps AS "(arceeps) As Reported Core - Basic EPS Effect",
    comp_na_daily_all.funda.autxr AS "(autxr) Appropriations to Untaxed Reserves",
    comp_na_daily_all.funda.balr AS "(balr) Benefits Assumed - Life",
    comp_na_daily_all.funda.banlr AS "(banlr) Benefits Assumed - Nonlife",
    comp_na_daily_all.funda.batr AS "(batr) Benefits Assumed - Total",
    comp_na_daily_all.funda.bcef AS "(bcef) Brokerage, Clearing and Exchange Fees",
    comp_na_daily_all.funda.bclr AS "(bclr) Benefits Ceded - Life",
    comp_na_daily_all.funda.bcltbl AS "(bcltbl) Benefits and Claims - Total (Business Line)",
    comp_na_daily_all.funda.bcnlr AS "(bcnlr) Benefits Ceded - Nonlife",
    comp_na_daily_all.funda.bcrbl AS "(bcrbl) Benefits and Claims - Reinsurance (Business Line)",
    comp_na_daily_all.funda.bct AS "(bct) Benefits and Claims - Total (Insurance)",
    comp_na_daily_all.funda.bctbl AS "(bctbl) Benefits and Claims - Other (Business Line)",
    comp_na_daily_all.funda.bctr AS "(bctr) Benefits Ceded - Total",
    comp_na_daily_all.funda.bltbl AS "(bltbl) Benefits - Life - Total (Business Line)",
    comp_na_daily_all.funda.cbi AS "(cbi) Claims Incurred - Insurance",
    comp_na_daily_all.funda.cdpac AS "(cdpac) Capitalized Deferred Polcy Acquisition Costs",
    comp_na_daily_all.funda.cfbd AS "(cfbd) Commissions and Fees - (Broker/Dealer)",
    comp_na_daily_all.funda.cfere AS "(cfere) Commissions and Fees - (Real Estate)",
    comp_na_daily_all.funda.cfo AS "(cfo) Commissions and Fees - Other",
    comp_na_daily_all.funda.cfpdo AS "(cfpdo) Commissions and Fees Paid - Other",
    comp_na_daily_all.funda.cga AS "(cga) Capital Gains - After-Tax",
    comp_na_daily_all.funda.cgri AS "(cgri) Capital Gains - Realized (Insurance)",
    comp_na_daily_all.funda.cgti AS "(cgti) Capital Gains - Total (Insurance)",
    comp_na_daily_all.funda.cgui AS "(cgui) Capital Gains - Unrealized (Insurance)",
    comp_na_daily_all.funda.cibegni AS "(cibegni) Comp Inc - Beginning Net Income",
    comp_na_daily_all.funda.cicurr AS "(cicurr) Comp Inc - Currency Trans Adj",
    comp_na_daily_all.funda.cidergl AS "(cidergl) Comp Inc - Derivative Gains/Losses",
    comp_na_daily_all.funda.ciother AS "(ciother) Comp Inc - Other Adj",
    comp_na_daily_all.funda.cipen AS "(cipen) Comp Inc - Minimum Pension Adj",
    comp_na_daily_all.funda.cisecgl AS "(cisecgl) Comp Inc - Securities Gains/Losses",
    comp_na_daily_all.funda.citotal AS "(citotal) Comprehensive Income - Parent",
    comp_na_daily_all.funda.cnltbl AS "(cnltbl) Claims - Non-Life - Total (Business Line)",
    comp_na_daily_all.funda.cogs AS "(cogs) Cost of Goods Sold",
    comp_na_daily_all.funda.cpcbl AS "(cpcbl) Commercial Property and Casualty Claims (Business Line)",
    comp_na_daily_all.funda.cpdoi AS "(cpdoi) Claims Paid - Other",
    comp_na_daily_all.funda.cpnli AS "(cpnli) Claims Paid - Non-Life",
    comp_na_daily_all.funda.cppbl AS "(cppbl) Commercial Property and Casualty Premiums (Business Line)",
    comp_na_daily_all.funda.cprei AS "(cprei) Claims Paid - Reinsurance",
    comp_na_daily_all.funda.cstke AS "(cstke) Common Stock Equivalents - Dollar Savings",
    comp_na_daily_all.funda.dbi AS "(dbi) Death Benefits - Insurance",
    comp_na_daily_all.funda.dfxa AS "(dfxa) Depreciation of Tangible Fixed Assets",
    comp_na_daily_all.funda.diladj AS "(diladj) Dilution Adjustment",
    comp_na_daily_all.funda.dilavx AS "(dilavx) Dilution Available - Excluding Extraordinary Items",
    comp_na_daily_all.funda.do AS "(do) Discontinued Operations",
    comp_na_daily_all.funda.donr AS "(donr) Nonrecurring Disc Operations",
    comp_na_daily_all.funda.dp AS "(dp) Depreciation and Amortization",
    comp_na_daily_all.funda.dpret AS "(dpret) Depr/Amort of Property",
    comp_na_daily_all.funda.dtea AS "(dtea) Extinguishment of Debt After-tax",
    comp_na_daily_all.funda.dted AS "(dted) Extinguishment of Debt Diluted EPS Effect",
    comp_na_daily_all.funda.dteeps AS "(dteeps) Extinguishment of Debt Basic EPS Effect",
    comp_na_daily_all.funda.dtep AS "(dtep) Extinguishment of Debt Pretax",
    comp_na_daily_all.funda.dvc AS "(dvc) Dividends Common/Ordinary",
    comp_na_daily_all.funda.dvdnp AS "(dvdnp) Dividends Declared and Not Provided",
    comp_na_daily_all.funda.dvp AS "(dvp) Dividends - Preferred/Preference",
    comp_na_daily_all.funda.dvpd AS "(dvpd) Cash Dividends Paid",
    comp_na_daily_all.funda.dvpdp AS "(dvpdp) Dividends and Bonuses Paid Policyholders",
    comp_na_daily_all.funda.dvrpiv AS "(dvrpiv) Dividends Received from Permanent Investments",
    comp_na_daily_all.funda.dvrre AS "(dvrre) Development Revenue (Real Estate)",
    comp_na_daily_all.funda.dvsco AS "(dvsco) Dividends - Share Capital - Other",
    comp_na_daily_all.funda.dvt AS "(dvt) Dividends - Total",
    comp_na_daily_all.funda.ebit AS "(ebit) Earnings Before Interest and Taxes",
    comp_na_daily_all.funda.ebitda AS "(ebitda) Earnings Before Interest",
    comp_na_daily_all.funda.eiea AS "(eiea) Equity in Earnings - After-Tax",
    comp_na_daily_all.funda.emol AS "(emol) Directors'' Emoluments",
    comp_na_daily_all.funda.epsfi AS "(epsfi) Earnings Per Share (Diluted) - Including Extraordinary Items",
    comp_na_daily_all.funda.epsfx AS "(epsfx) Earnings Per Share (Diluted) - Excluding Extraordinary Items",
    comp_na_daily_all.funda.epspi AS "(epspi) Earnings Per Share (Basic) - Including Extraordinary Items",
    comp_na_daily_all.funda.epspx AS "(epspx) Earnings Per Share (Basic) - Excluding Extraordinary Items",
    comp_na_daily_all.funda.esub AS "(esub) Equity in Earnings - Unconsolidated Subsidiaries",
    comp_na_daily_all.funda.fatd AS "(fatd) Fixed Assets and Investments - Disposals - Gain (Loss)",
    comp_na_daily_all.funda.fca AS "(fca) Foreign Exchange Income (Loss)",
    comp_na_daily_all.funda.ffo AS "(ffo) Funds From Operations (REIT)",
    comp_na_daily_all.funda.gbbl AS "(gbbl) Group Benefits (Business Line)",
    comp_na_daily_all.funda.gdwlam AS "(gdwlam) Goodwill Amortization",
    comp_na_daily_all.funda.gdwlia AS "(gdwlia) Impairments of Goodwill After-tax",
    comp_na_daily_all.funda.gdwlid AS "(gdwlid) Impairments of Goodwill Diluted EPS Effect",
    comp_na_daily_all.funda.gdwlieps AS "(gdwlieps) Impairments of Goodwill Basic EPS Effect",
    comp_na_daily_all.funda.gdwlip AS "(gdwlip) Impairments of Goodwill Pretax",
    comp_na_daily_all.funda.gla AS "(gla) Gain/Loss After-tax",
    comp_na_daily_all.funda.glcea AS "(glcea) Gain/Loss on Sale (Core Earnings Adjusted) After-tax",
    comp_na_daily_all.funda.glced AS "(glced) Gain/Loss on Sale (Core Earnings Adjusted) Diluted EPS",
    comp_na_daily_all.funda.glceeps AS "(glceeps) Gain/Loss on Sale (Core Earnings Adjusted) Basic EPS Effect",
    comp_na_daily_all.funda.glcep AS "(glcep) Gain/Loss on Sale (Core Earnings Adjusted) Pretax",
    comp_na_daily_all.funda.gld AS "(gld) Gain/Loss Diluted EPS Effect",
    comp_na_daily_all.funda.gleps AS "(gleps) Gain/Loss Basic EPS Effect",
    comp_na_daily_all.funda.glp AS "(glp) Gain/Loss Pretax",
    comp_na_daily_all.funda.gp AS "(gp) Gross Profit (Loss)",
    comp_na_daily_all.funda.gphbl AS "(gphbl) Group Premiums - Health (Business Line)",
    comp_na_daily_all.funda.gplbl AS "(gplbl) Group Premiums - Life (Business Line)",
    comp_na_daily_all.funda.gpobl AS "(gpobl) Group Premiums - Other (Business Line)",
    comp_na_daily_all.funda.gprbl AS "(gprbl) Group Premiums - Retirement Benefits (Business Line)",
    comp_na_daily_all.funda.gptbl AS "(gptbl) Group Premiums - Total (Business Line)",
    comp_na_daily_all.funda.gwo AS "(gwo) Goodwill Written Off",
    comp_na_daily_all.funda.hedgegl AS "(hedgegl) Gain/Loss on Ineffective Hedges",
    comp_na_daily_all.funda.ib AS "(ib) Income Before Extraordinary Items",
    comp_na_daily_all.funda.ibadj AS "(ibadj) Income Before Extraordinary Items - Adjusted for Common Stock Equivalents",
    comp_na_daily_all.funda.ibbl AS "(ibbl) Individual Benefits (Business Line)",
    comp_na_daily_all.funda.ibcom AS "(ibcom) Income Before Extraordinary Items - Available for Common",
    comp_na_daily_all.funda.ibki AS "(ibki) Investment Banking Income",
    comp_na_daily_all.funda.idiis AS "(idiis) Interest and Dividend Income - Investment Securities",
    comp_na_daily_all.funda.idilb AS "(idilb) Interest and Dividend Income - Loans/Claims/Advances - Banks",
    comp_na_daily_all.funda.idilc AS "(idilc) Interest and Dividend Income - Loans/Claims/Advances - Customers",
    comp_na_daily_all.funda.idis AS "(idis) Interest and Dividend Income - Sundry",
    comp_na_daily_all.funda.idist AS "(idist) Interest and Dividend Income - Short-Term Investments",
    comp_na_daily_all.funda.idit AS "(idit) Interest and Related Income - Total",
    comp_na_daily_all.funda.idits AS "(idits) Interest and Dividend Income - Trading Securities",
    comp_na_daily_all.funda.iire AS "(iire) Investment Income (Real Estate)",
    comp_na_daily_all.funda.initb AS "(initb) Income - Non-interest - Total (Bank)",
    comp_na_daily_all.funda.intc AS "(intc) Interest Capitalized",
    comp_na_daily_all.funda.iobd AS "(iobd) Income - Other (Broker Dealer)",
    comp_na_daily_all.funda.ioi AS "(ioi) Income - Other (Insurance)",
    comp_na_daily_all.funda.iore AS "(iore) Income - Other (Real Estate)",
    comp_na_daily_all.funda.ipabl AS "(ipabl) Individual Premiums - Annuity (Business Line)",
    comp_na_daily_all.funda.iphbl AS "(iphbl) Individual Premiums - Health (Business Line)",
    comp_na_daily_all.funda.iplbl AS "(iplbl) Individual Premiums - Life (Business Line)",
    comp_na_daily_all.funda.ipobl AS "(ipobl) Individual Premiums - Other (Business Line)",
    comp_na_daily_all.funda.iptbl AS "(iptbl) Individual Premiums - Total (Business Line)",
    comp_na_daily_all.funda.ipti AS "(ipti) Insurance Premiums - Total (Insurance)",
    comp_na_daily_all.funda.irei AS "(irei) Interest and Related Income - Reinsurance (Insurance)",
    comp_na_daily_all.funda.irent AS "(irent) Rental Income",
    comp_na_daily_all.funda.irii AS "(irii) Interest and Related Income (Insurance)",
    comp_na_daily_all.funda.irli AS "(irli) Interest and Related Income - Life (Insurance)",
    comp_na_daily_all.funda.irnli AS "(irnli) Interest and Related Income - Non-Life (Insurance)",
    comp_na_daily_all.funda.irsi AS "(irsi) Interest and Related Income - Sundry (Insurance)",
    comp_na_daily_all.funda.isgr AS "(isgr) Investment Securities - Gain (Loss) - Realized",
    comp_na_daily_all.funda.isgt AS "(isgt) Investment Securities - Gain (Loss) - Total",
    comp_na_daily_all.funda.isgu AS "(isgu) Investment Securities - Gain (Loss) - Unrealized",
    comp_na_daily_all.funda.itci AS "(itci) Investment Tax Credit (Income Account)",
    comp_na_daily_all.funda.ivi AS "(ivi) Investment Income - Total (Insurance)",
    comp_na_daily_all.funda.li AS "(li) Leasing Income",
    comp_na_daily_all.funda.llrci AS "(llrci) Loan Loss Recoveries - Credited to Income",
    comp_na_daily_all.funda.llrcr AS "(llrcr) Loan Loss Recoveries - Credited to Reserves",
    comp_na_daily_all.funda.llwoci AS "(llwoci) Loan Loss Written Off - Charged to Income",
    comp_na_daily_all.funda.llwocr AS "(llwocr) Loan Loss Written Off - Charged to Reserves",
    comp_na_daily_all.funda.lst AS "(lst) Life Insurance Surrenders and Terminations",
    comp_na_daily_all.funda.mii AS "(mii) Noncontrolling Interest (Income Account)",
    comp_na_daily_all.funda.nco AS "(nco) Net Charge-Offs",
    comp_na_daily_all.funda.nfsr AS "(nfsr) Non-Financial Services Revenue",
    comp_na_daily_all.funda.ni AS "(ni) Net Income (Loss)",
    comp_na_daily_all.funda.niadj AS "(niadj) Net Income Adjusted for Common/Ordinary Stock (Capital) Equivalents",
    comp_na_daily_all.funda.nieci AS "(nieci) Net Income Effect Capitalized Interest",
    comp_na_daily_all.funda.niint AS "(niint) Net Interest Income",
    comp_na_daily_all.funda.niit AS "(niit) Net Interest Income (Tax Equivalent)",
    comp_na_daily_all.funda.nim AS "(nim) Net Interest Margin",
    comp_na_daily_all.funda.nio AS "(nio) Net Items - Other",
    comp_na_daily_all.funda.nit AS "(nit) Net Item - Total",
    comp_na_daily_all.funda.nits AS "(nits) Net Income - Total (Statutory)",
    comp_na_daily_all.funda.nopi AS "(nopi) Nonoperating Income (Expense)",
    comp_na_daily_all.funda.nopio AS "(nopio) Nonoperating Income (Expense) - Other",
    comp_na_daily_all.funda.nrtxt AS "(nrtxt) Nonrecurring Income Taxes After-tax",
    comp_na_daily_all.funda.nrtxtd AS "(nrtxtd) Nonrecurring Income Tax Diluted EPS Effect",
    comp_na_daily_all.funda.nrtxteps AS "(nrtxteps) Nonrecurring Income Tax Basic EPS Effect",
    comp_na_daily_all.funda.oiadp AS "(oiadp) Operating Income After Depreciation",
    comp_na_daily_all.funda.oibdp AS "(oibdp) Operating Income Before Depreciation",
    comp_na_daily_all.funda.opeps AS "(opeps) Earnings Per Share from Operations",
    comp_na_daily_all.funda.opili AS "(opili) Operating Income - Life",
    comp_na_daily_all.funda.opincar AS "(opincar) Operating Income - As Reported",
    comp_na_daily_all.funda.opini AS "(opini) Operating Income - Non-Life",
    comp_na_daily_all.funda.opioi AS "(opioi) Operating Income - Other",
    comp_na_daily_all.funda.opiri AS "(opiri) Operating Income - Reinsurance",
    comp_na_daily_all.funda.opiti AS "(opiti) Operating Income - Total",
    comp_na_daily_all.funda.oprepsx AS "(oprepsx) Earnings Per Share - Diluted - from Operations",
    comp_na_daily_all.funda.palr AS "(palr) Premiums Assumed - Life",
    comp_na_daily_all.funda.panlr AS "(panlr) Premiums Assumed - Nonlife",
    comp_na_daily_all.funda.patr AS "(patr) Premiums Assumed - Total",
    comp_na_daily_all.funda.pcl AS "(pcl) Provision - Credit Losses (Income Account)",
    comp_na_daily_all.funda.pclr AS "(pclr) Premiums Ceded - Life",
    comp_na_daily_all.funda.pcnlr AS "(pcnlr) Premiums Ceded - Nonlife",
    comp_na_daily_all.funda.pctr AS "(pctr) Premiums Ceded - Total",
    comp_na_daily_all.funda.pi AS "(pi) Pretax Income",
    comp_na_daily_all.funda.pidom AS "(pidom) Pretax Income - Domestic",
    comp_na_daily_all.funda.pifo AS "(pifo) Pretax Income - Foreign",
    comp_na_daily_all.funda.pll AS "(pll) Provision for Loan/Asset Losses",
    comp_na_daily_all.funda.pltbl AS "(pltbl) Premiums - Life - Total (Business Line)",
    comp_na_daily_all.funda.pnca AS "(pnca) Core Pension Adjustment",
    comp_na_daily_all.funda.pncad AS "(pncad) Core Pension Adjustment Diluted EPS Effect",
    comp_na_daily_all.funda.pncaeps AS "(pncaeps) Core Pension Adjustment Basic EPS Effect",
    comp_na_daily_all.funda.pncia AS "(pncia) Core Pension Interest Adjustment After-tax",
    comp_na_daily_all.funda.pncid AS "(pncid) Core Pension Interest Adjustment Diluted EPS Effect",
    comp_na_daily_all.funda.pncieps AS "(pncieps) Core Pension Interest Adjustment Basic EPS Effect",
    comp_na_daily_all.funda.pncip AS "(pncip) Core Pension Interest Adjustment Pretax",
    comp_na_daily_all.funda.pncwia AS "(pncwia) Core Pension w/o Interest Adjustment After-tax",
    comp_na_daily_all.funda.pncwid AS "(pncwid) Core Pension w/o Interest Adjustment Diluted EPS Effect",
    comp_na_daily_all.funda.pncwieps AS "(pncwieps) Core Pension w/o Interest Adjustment Basic EPS Effect",
    comp_na_daily_all.funda.pncwip AS "(pncwip) Core Pension w/o Interest Adjustment Pretax",
    comp_na_daily_all.funda.pnlbl AS "(pnlbl) Premiums - Nonlife - Total (Business Line)",
    comp_na_daily_all.funda.pnli AS "(pnli) Premiums Written - Non-Life",
    comp_na_daily_all.funda.pobl AS "(pobl) Premiums - Other (Business Line)",
    comp_na_daily_all.funda.ppcbl AS "(ppcbl) Personal Property and Casualty Claims (Business Line)",
    comp_na_daily_all.funda.pppabl AS "(pppabl) Personal Property and Casualty Premiums - Automobile (Business Line)",
    comp_na_daily_all.funda.ppphbl AS "(ppphbl) Personal Property and Casualty Premiums - Homeowners (Business Line)",
    comp_na_daily_all.funda.pppobl AS "(pppobl) Personal Property and Casualty Premiums - Other (Business Line)",
    comp_na_daily_all.funda.ppptbl AS "(ppptbl) Personal Property & Casualty Premiums - Total (Business Line)",
    comp_na_daily_all.funda.prca AS "(prca) Core Post Retirement Adjustment",
    comp_na_daily_all.funda.prcad AS "(prcad) Core Post Retirement Adjustment Diluted EPS Effect",
    comp_na_daily_all.funda.prcaeps AS "(prcaeps) Core Post Retirement Adjustment Basic EPS Effect",
    comp_na_daily_all.funda.prebl AS "(prebl) Premiums - Reinsurance (Business Line)",
    comp_na_daily_all.funda.pri AS "(pri) Premiums Written - Reinsurance",
    comp_na_daily_all.funda.ptbl AS "(ptbl) Premiums - Total (Business Line)",
    comp_na_daily_all.funda.ptran AS "(ptran) Principal Transactions",
    comp_na_daily_all.funda.pvo AS "(pvo) Provision - Other",
    comp_na_daily_all.funda.pvon AS "(pvon) Provisions - Other (Net)",
    comp_na_daily_all.funda.pwoi AS "(pwoi) Premiums Written - Other",
    comp_na_daily_all.funda.rca AS "(rca) Restructuring Costs After-tax",
    comp_na_daily_all.funda.rcd AS "(rcd) Restructuring Costs Diluted EPS Effect",
    comp_na_daily_all.funda.rceps AS "(rceps) Restructuring Costs Basic EPS Effect",
    comp_na_daily_all.funda.rcp AS "(rcp) Restructuring Costs Pretax",
    comp_na_daily_all.funda.rdip AS "(rdip) In Process R&D Expense",
    comp_na_daily_all.funda.rdipa AS "(rdipa) In Process R&D Expense After-tax",
    comp_na_daily_all.funda.rdipd AS "(rdipd) In Process R&D Expense Diluted EPS Effect",
    comp_na_daily_all.funda.rdipeps AS "(rdipeps) In Process R&D Expense Basic EPS Effect",
    comp_na_daily_all.funda.revt AS "(revt) Revenue - Total",
    comp_na_daily_all.funda.ris AS "(ris) Revenue/Income - Sundry",
    comp_na_daily_all.funda.rmum AS "(rmum) Auditors'' Remuneraton",
    comp_na_daily_all.funda.rra AS "(rra) Reversal - Restructruring/Acquisition Aftertax",
    comp_na_daily_all.funda.rrd AS "(rrd) Reversal - Restructuring/Acq Diluted EPS Effect",
    comp_na_daily_all.funda.rrp AS "(rrp) Reversal - Restructruring/Acquisition Pretax",
    comp_na_daily_all.funda.sale AS "(sale) Sales/Turnover (Net)",
    comp_na_daily_all.funda.seta AS "(seta) Settlement (Litigation/Insurance) After-tax",
    comp_na_daily_all.funda.setd AS "(setd) Settlement (Litigation/Insurance) Diluted EPS Effect",
    comp_na_daily_all.funda.seteps AS "(seteps) Settlement (Litigation/Insurance) Basic EPS Effect",
    comp_na_daily_all.funda.setp AS "(setp) Settlement (Litigation/Insurance) Pretax",
    comp_na_daily_all.funda.spce AS "(spce) S&P Core Earnings",
    comp_na_daily_all.funda.spced AS "(spced) S&P Core Earnings EPS Diluted",
    comp_na_daily_all.funda.spceeps AS "(spceeps) S&P Core Earnings EPS Basic",
    comp_na_daily_all.funda.spi AS "(spi) Special Items",
    comp_na_daily_all.funda.spid AS "(spid) Other Special Items Diluted EPS Effect",
    comp_na_daily_all.funda.spieps AS "(spieps) Other Special Items Basic EPS Effect",
    comp_na_daily_all.funda.spioa AS "(spioa) Other Special Items After-tax",
    comp_na_daily_all.funda.spiop AS "(spiop) Other Special Items Pretax",
    comp_na_daily_all.funda.sret AS "(sret) Gain/Loss on Sale of Property",
    comp_na_daily_all.funda.stkco AS "(stkco) Stock Compensation Expense",
    comp_na_daily_all.funda.stkcpa AS "(stkcpa) After-tax stock compensation",
    comp_na_daily_all.funda.tdsg AS "(tdsg) Trading/Dealing Securities - Gain (Loss)",
    comp_na_daily_all.funda.tf AS "(tf) Trust Fees",
    comp_na_daily_all.funda.tie AS "(tie) Interest Expense - Total (Financial Services)",
    comp_na_daily_all.funda.tii AS "(tii) Interest Income - Total (Financial Services)",
    comp_na_daily_all.funda.txc AS "(txc) Income Taxes - Current",
    comp_na_daily_all.funda.txdfed AS "(txdfed) Deferred Taxes-Federal",
    comp_na_daily_all.funda.txdfo AS "(txdfo) Deferred Taxes-Foreign",
    comp_na_daily_all.funda.txdi AS "(txdi) Income Taxes - Deferred",
    comp_na_daily_all.funda.txds AS "(txds) Deferred Taxes-State",
    comp_na_daily_all.funda.txeqa AS "(txeqa) Tax - Equivalent Adjustment",
    comp_na_daily_all.funda.txeqii AS "(txeqii) Tax - Equivalent Interest Income (Gross)",
    comp_na_daily_all.funda.txfed AS "(txfed) Income Taxes - Federal",
    comp_na_daily_all.funda.txfo AS "(txfo) Income Taxes - Foreign",
    comp_na_daily_all.funda.txo AS "(txo) Income Taxes - Other",
    comp_na_daily_all.funda.txs AS "(txs) Income Taxes - State",
    comp_na_daily_all.funda.txt AS "(txt) Income Taxes - Total",
    comp_na_daily_all.funda.txva AS "(txva) Value Added Taxes",
    comp_na_daily_all.funda.txw AS "(txw) Excise Taxes",
    comp_na_daily_all.funda.udpfa AS "(udpfa) Depreciation of Fixed Assets",
    comp_na_daily_all.funda.udvp AS "(udvp) Preferred Dividend Requirements",
    comp_na_daily_all.funda.ugi AS "(ugi) Gross Income (Income Before Interest Charges)",
    comp_na_daily_all.funda.uniami AS "(uniami) Net Income before Extraordinary Items and after Noncontrolling Interest",
    comp_na_daily_all.funda.unopinc AS "(unopinc) Nonoperating Income (Net) - Other",
    comp_na_daily_all.funda.uopi AS "(uopi) Operating Income - Total - Utility",
    comp_na_daily_all.funda.updvp AS "(updvp) Preference Dividend Requirements*",
    comp_na_daily_all.funda.uspi AS "(uspi) Special Items",
    comp_na_daily_all.funda.usubdvp AS "(usubdvp) Subsidiary Preferred Dividends",
    comp_na_daily_all.funda.utme AS "(utme) Maintenance Expense - Total",
    comp_na_daily_all.funda.utxfed AS "(utxfed) Current Taxes - Federal (Operating)",
    comp_na_daily_all.funda.uxinst AS "(uxinst) Interest On Short-Term Debt - Utility",
    comp_na_daily_all.funda.uxintd AS "(uxintd) Interest on Long-Term Debt*",
    comp_na_daily_all.funda.wda AS "(wda) Writedowns After-tax",
    comp_na_daily_all.funda.wdd AS "(wdd) Writedowns Diluted EPS Effect",
    comp_na_daily_all.funda.wdeps AS "(wdeps) Writedowns Basic EPS Effect",
    comp_na_daily_all.funda.wdp AS "(wdp) Writedowns Pretax",
    comp_na_daily_all.funda.xad AS "(xad) Advertising Expense",
    comp_na_daily_all.funda.xago AS "(xago) Administrative and General Expense - Other",
    comp_na_daily_all.funda.xagt AS "(xagt) Administrative and General Expense - Total",
    comp_na_daily_all.funda.xcom AS "(xcom) Communications Expense",
    comp_na_daily_all.funda.xcomi AS "(xcomi) Commissions Expense (Insurance)",
    comp_na_daily_all.funda.xdepl AS "(xdepl) Depletion Expense (Schedule VI)",
    comp_na_daily_all.funda.xdp AS "(xdp) Depreciation Expense (Schedule VI)",
    comp_na_daily_all.funda.xdvre AS "(xdvre) Expense - Development (Real Estate)",
    comp_na_daily_all.funda.xeqo AS "(xeqo) Equipment and Occupancy Expense",
    comp_na_daily_all.funda.xi AS "(xi) Extraordinary Items",
    comp_na_daily_all.funda.xido AS "(xido) Extraordinary Items and Discontinued Operations",
    comp_na_daily_all.funda.xindb AS "(xindb) Interest Expense - Deposits - Banks",
    comp_na_daily_all.funda.xindc AS "(xindc) Interest Expense - Deposits - Customer",
    comp_na_daily_all.funda.xins AS "(xins) Interest Expense - Sundry",
    comp_na_daily_all.funda.xinst AS "(xinst) Interest Expense - Short-Term Borrowings",
    comp_na_daily_all.funda.xint AS "(xint) Interest and Related Expense - Total",
    comp_na_daily_all.funda.xintd AS "(xintd) Interest Expense - Long-Term Debt",
    comp_na_daily_all.funda.xintopt AS "(xintopt) Implied Option Expense",
    comp_na_daily_all.funda.xivi AS "(xivi) Investment Expense (Insurance)",
    comp_na_daily_all.funda.xivre AS "(xivre) Expense - Investment (Real Estate)",
    comp_na_daily_all.funda.xlr AS "(xlr) Staff Expense - Total",
    comp_na_daily_all.funda.xnbi AS "(xnbi) Other Insurance Expense",
    comp_na_daily_all.funda.xnf AS "(xnf) Non-Financial Services Expense",
    comp_na_daily_all.funda.xnins AS "(xnins) Other Expense - Noninsurance",
    comp_na_daily_all.funda.xnitb AS "(xnitb) Expense - Noninterest - Total (Bank)",
    comp_na_daily_all.funda.xobd AS "(xobd) Expense - Other (Broker/Dealer)",
    comp_na_daily_all.funda.xoi AS "(xoi) Expenses - Other (Insurance)",
    comp_na_daily_all.funda.xopr AS "(xopr) Operating Expenses - Total",
    comp_na_daily_all.funda.xoprar AS "(xoprar) Operatings Expenses - As Reported",
    comp_na_daily_all.funda.xoptd AS "(xoptd) Implied Option EPS Diluted",
    comp_na_daily_all.funda.xopteps AS "(xopteps) Implied Option EPS Basic",
    comp_na_daily_all.funda.xore AS "(xore) Expense - Other (Real Estate)",
    comp_na_daily_all.funda.xpr AS "(xpr) Pension and Retirement Expense",
    comp_na_daily_all.funda.xrd AS "(xrd) Research and Development Expense",
    comp_na_daily_all.funda.xrent AS "(xrent) Rental Expense",
    comp_na_daily_all.funda.xs AS "(xs) Expense - Sundry",
    comp_na_daily_all.funda.xsga AS "(xsga) Selling, General and Administrative Expense",
    comp_na_daily_all.funda.xstf AS "(xstf) Staff Expense (Income Account)",
    comp_na_daily_all.funda.xstfo AS "(xstfo) Staff Expense - Other",
    comp_na_daily_all.funda.xstfws AS "(xstfws) Staff Expense - Wages and Salaries",
    comp_na_daily_all.funda.xt AS "(xt) Expense - Total",
    comp_na_daily_all.funda.xuw AS "(xuw) Other Underwriting Expenses - Insurance",
    comp_na_daily_all.funda.xuwli AS "(xuwli) Underwriting Expense - Life",
    comp_na_daily_all.funda.xuwnli AS "(xuwnli) Underwriting Expense - Non-Life",
    comp_na_daily_all.funda.xuwoi AS "(xuwoi) Underwriting Expense - Other",
    comp_na_daily_all.funda.xuwrei AS "(xuwrei) Underwriting Expense - Reinsurance",
    comp_na_daily_all.funda.xuwti AS "(xuwti) Underwriting Expense - Total",
    comp_na_daily_all.funda.afudcc AS "(afudcc) Allowance for Funds Used During Construction (Cash Flow)",
    comp_na_daily_all.funda.afudci AS "(afudci) Allowance for Funds Used During Construction (Investing) (Cash Flow)",
    comp_na_daily_all.funda.amc AS "(amc) Amortization (Cash Flow) - Utility",
    comp_na_daily_all.funda.aoloch AS "(aoloch) Assets and Liabilities - Other - Net Change",
    comp_na_daily_all.funda.apalch AS "(apalch) Accounts Payable and Accrued Liabilities - Increase/(Decrease)",
    comp_na_daily_all.funda.aqc AS "(aqc) Acquisitions",
    comp_na_daily_all.funda.capx AS "(capx) Capital Expenditures",
    comp_na_daily_all.funda.capxv AS "(capxv) Capital Expend Property, Plant and Equipment Schd V",
    comp_na_daily_all.funda.cdvc AS "(cdvc) Cash Dividends on Common Stock (Cash Flow)",
    comp_na_daily_all.funda.chech AS "(chech) Cash and Cash Equivalents - Increase/(Decrease)",
    comp_na_daily_all.funda.depc AS "(depc) Depreciation and Depletion (Cash Flow)",
    comp_na_daily_all.funda.dlcch AS "(dlcch) Current Debt - Changes",
    comp_na_daily_all.funda.dltis AS "(dltis) Long-Term Debt - Issuance",
    comp_na_daily_all.funda.dltr AS "(dltr) Long-Term Debt - Reduction",
    comp_na_daily_all.funda.dpc AS "(dpc) Depreciation and Amortization (Cash Flow)",
    comp_na_daily_all.funda.dv AS "(dv) Cash Dividends (Cash Flow)",
    comp_na_daily_all.funda.esubc AS "(esubc) Equity in Net Loss - Earnings",
    comp_na_daily_all.funda.exre AS "(exre) Exchange Rate Effect",
    comp_na_daily_all.funda.fiao AS "(fiao) Financing Activities - Other",
    comp_na_daily_all.funda.fincf AS "(fincf) Financing Activities - Net Cash Flow",
    comp_na_daily_all.funda.fopo AS "(fopo) Funds from Operations - Other",
    comp_na_daily_all.funda.fopox AS "(fopox) Funds from Operations - Other excluding Option Tax Benefit",
    comp_na_daily_all.funda.fopt AS "(fopt) Funds From Operations - Total",
    comp_na_daily_all.funda.fsrco AS "(fsrco) Sources of Funds - Other",
    comp_na_daily_all.funda.fsrct AS "(fsrct) Sources of Funds - Total",
    comp_na_daily_all.funda.fuseo AS "(fuseo) Uses of Funds - Other",
    comp_na_daily_all.funda.fuset AS "(fuset) Uses of Funds - Total",
    comp_na_daily_all.funda.ibc AS "(ibc) Income Before Extraordinary Items (Cash Flow)",
    comp_na_daily_all.funda.intpn AS "(intpn) Interest Paid - Net",
    comp_na_daily_all.funda.invch AS "(invch) Inventory - Decrease (Increase)",
    comp_na_daily_all.funda.itcc AS "(itcc) Investment Tax Credit - Net (Cash Flow) - Utility",
    comp_na_daily_all.funda.ivaco AS "(ivaco) Investing Activities - Other",
    comp_na_daily_all.funda.ivch AS "(ivch) Increase in Investments",
    comp_na_daily_all.funda.ivncf AS "(ivncf) Investing Activities - Net Cash Flow",
    comp_na_daily_all.funda.ivstch AS "(ivstch) Short-Term Investments - Change",
    comp_na_daily_all.funda.oancf AS "(oancf) Operating Activities - Net Cash Flow",
    comp_na_daily_all.funda.pdvc AS "(pdvc) Cash Dividends on Preferred/Preference Stock (Cash Flow)",
    comp_na_daily_all.funda.prstkc AS "(prstkc) Purchase of Common and Preferred Stock",
    comp_na_daily_all.funda.prstkcc AS "(prstkcc) Purchase of Common Stock (Cash Flow)",
    comp_na_daily_all.funda.prstkpc AS "(prstkpc) Purchase of Preferred/Preference Stock (Cash Flow)",
    comp_na_daily_all.funda.recch AS "(recch) Accounts Receivable - Decrease (Increase)",
    comp_na_daily_all.funda.scstkc AS "(scstkc) Sale of Common Stock (Cash Flow)",
    comp_na_daily_all.funda.siv AS "(siv) Sale of Investments",
    comp_na_daily_all.funda.sppe AS "(sppe) Sale of Property",
    comp_na_daily_all.funda.sppiv AS "(sppiv) Sale of Property, Plant and Equipment and Investments - Gain (Loss)",
    comp_na_daily_all.funda.spstkc AS "(spstkc) Sale of Preferred/Preference Stock (Cash Flow)",
    comp_na_daily_all.funda.sstk AS "(sstk) Sale of Common and Preferred Stock",
    comp_na_daily_all.funda.tdc AS "(tdc) Deferred Income Taxes - Net (Cash Flow)",
    comp_na_daily_all.funda.tsafc AS "(tsafc) Total Sources/Applications of Funds (Cash Flow)",
    comp_na_daily_all.funda.txach AS "(txach) Income Taxes - Accrued - Increase/(Decrease)",
    comp_na_daily_all.funda.txbco AS "(txbco) Excess Tax Benefit Stock Options - Cash Flow Operating",
    comp_na_daily_all.funda.txbcof AS "(txbcof) Excess Tax Benefit of Stock Options - Cash Flow Financing",
    comp_na_daily_all.funda.txdc AS "(txdc) Deferred Taxes (Cash Flow)",
    comp_na_daily_all.funda.txpd AS "(txpd) Income Taxes Paid",
    comp_na_daily_all.funda.uaoloch AS "(uaoloch) Other Assets and Liabilities - Net Change (Statement of Cash Flows)",
    comp_na_daily_all.funda.udfcc AS "(udfcc) Deferred Fuel - Increase (Decrease) (Statement of Cash Flows)",
    comp_na_daily_all.funda.ufretsd AS "(ufretsd) Funds for Retirement of Securities and Short-Term Debt (Cash Flow)",
    comp_na_daily_all.funda.unwcc AS "(unwcc) Working Capital (Use) - Increase (Decrease) (Cash Flow)",
    comp_na_daily_all.funda.uois AS "(uois) Other Internal Sources - Net (Cash Flow)",
    comp_na_daily_all.funda.ustdnc AS "(ustdnc) Short-Term Debt - Decrease (Increase) (Cash Flow)",
    comp_na_daily_all.funda.utfdoc AS "(utfdoc) Total Funds From Operations (Cash Flow)",
    comp_na_daily_all.funda.utfosc AS "(utfosc) Total Funds from Outside Sources (Cash Flow)",
    comp_na_daily_all.funda.uwkcapc AS "(uwkcapc) Working Capital (Source) - Decrease (Increase) (Cash Flow)",
    comp_na_daily_all.funda.wcapc AS "(wcapc) Working Capital Change - Other - Increase/(Decrease)",
    comp_na_daily_all.funda.wcapch AS "(wcapch) Working Capital Change - Total",
    comp_na_daily_all.funda.xidoc AS "(xidoc) Extraordinary Items and Discontinued Operations (Cash Flow)"

FROM comp_na_daily_all.funda
LEFT JOIN (
    SELECT
        gvkey
    FROM comp_na_daily_all.company
) AS id_table 

ON comp_na_daily_all.funda.gvkey = id_table.gvkey

WHERE comp_na_daily_all.funda.datadate BETWEEN
    '2010-01-01'::date AND '2025-09-30'::date

AND ("comp_na_daily_all"."funda"."consol" = ANY (ARRAY['C']) AND "comp_na_daily_all"."funda"."indfmt" = ANY (ARRAY['INDL','FS']) AND "comp_na_daily_all"."funda"."datafmt" = ANY (ARRAY['STD']) AND "comp_na_daily_all"."funda"."curcd" = ANY (ARRAY['USD']) AND "comp_na_daily_all"."funda"."costat" = ANY (ARRAY['A']))
